### ISSUE TITLE
发布订阅模式代码示例有点小问题

### ISSUE THREAD

**Issue by dxcqcv** [Molunerfinn/es6-learning#2]
```
import bus from './pubsub.ts'
const people = function (val) {
  console.log('我收到了新的商品通知：', val) //那么这里的结果是我收到了新的商品通知：[object Object]？？
}

bus.on('newItem', people) 

const merchant = function (val) { 
  const item = {
    item: val
  }
  bus.emit('newItem', item) // 这里把对象item传过去？
}

merchant('Book') 
```

如注释，是不是应该直接传val，或者在`people`函数处解构一下

**Comment by Molunerfinn** [comment]
没啥问题啊...你传的是一个对象`{item: 'book'}`，如果你想要看到`book`，你的console可以`console.log(val.item)`
按你的代码原样输出：
![image](https://user-images.githubusercontent.com/12621342/43236056-ad35946c-90b5-11e8-9375-7eef4f878eaa.png)
如果只想看到`book`：
![image](https://user-images.githubusercontent.com/12621342/43236065-c4e4704c-90b5-11e8-9949-2bd4b1290a81.png)

发布订阅模式不关心你传递了什么数据，所以解构也应该由你来实现。

![image](https://user-images.githubusercontent.com/12621342/43236101-f20e556a-90b5-11e8-9399-f304bfc672a9.png)
